# This Makefile is generated by omake: https://github.com/ouonline/omake.git

CC := gcc

ifeq ($(debug), y)
	CFLAGS += -g
else
	CFLAGS += -O2 -DNDEBUG
endif

AR := ar

TARGET := libutils_shared.so libutils_static.a

.PHONY: all clean

all: $(TARGET)

rbtree.c.omake_dep_0.o: rbtree.c
	$(CC) $(CFLAGS) -Wall -Werror -Wextra -fPIC -c $< -o $@

time_utils.c.omake_dep_0.o: time_utils.c
	$(CC) $(CFLAGS) -Wall -Werror -Wextra -fPIC -c $< -o $@

hash.c.omake_dep_0.o: hash.c
	$(CC) $(CFLAGS) -Wall -Werror -Wextra -fPIC -c $< -o $@

str_utils.c.omake_dep_0.o: str_utils.c
	$(CC) $(CFLAGS) -Wall -Werror -Wextra -fPIC -c $< -o $@

utils_shared_OBJS := rbtree.c.omake_dep_0.o time_utils.c.omake_dep_0.o hash.c.omake_dep_0.o str_utils.c.omake_dep_0.o

libutils_shared.so: $(utils_shared_OBJS)
	$(CC) $(CFLAGS) -shared -o $@ $^

utils_static_OBJS := rbtree.c.omake_dep_0.o time_utils.c.omake_dep_0.o hash.c.omake_dep_0.o str_utils.c.omake_dep_0.o

libutils_static.a: $(utils_static_OBJS)
	$(AR) rc $@ $^

clean:
	rm -f $(TARGET) $(utils_shared_OBJS) $(utils_static_OBJS)
